version: '3'
services:
  app:
    build: .
    ports:
      - "8337:8337"
    depends_on:
      - db
    environment:
      - DATABASE_URL=pgsql://user:password@db:5432/database

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=database